name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v4
    - name: Build the base docker image
      run: docker build -t cmaketemplate:base $(pwd)/docker/base
      
    - uses: actions/checkout@v4
    - name: Build the builder docker image
      run: docker build -t cmaketemplate:builder $(pwd)/docker/builder
