name: Docker Image CI
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ImageName: cmaketemplate
    steps:

    - uses: actions/checkout@v4

    - name: Build the $ImageName:$Tag docker image
      run: docker build -t $ImageName:$Tag $(pwd)/docker/$Tag
      env:
        Tag: base

    - name: Build the $ImageName:$Tag docker image
      run: docker build -t $ImageName:$Tag $(pwd)/docker/$Tag
      env:
        Tag: builder      

    - name: Build the project ($BuildType)
      run: docker run --rm --entrypoint sh -v $(pwd):/work -w /work $ImageName:builder -c "mkdir -p /work/build/$BuildType && cd /work/build/$BuildType && cmake -DCMAKE_BUILD_TYPE=$BuildType ../.. && make && make test && make gcovr && make cppcheck && make valgrind && make package && make doxygen"
      env:
        BuildType: Debug

    - name: Build the project ($BuildType)
      run: docker run --rm --entrypoint sh -v $(pwd):/work -w /work $ImageName:builder -c "mkdir -p /work/build/$BuildType && cd /work/build/$BuildType && cmake -DCMAKE_BUILD_TYPE=$BuildType ../.. && make && make test && make gcovr && make cppcheck && make valgrind && make package && make doxygen"
      env:
        BuildType: Release

    - name: Copy .deb to runtime docker context
      run: cp $(pwd)/build/Release/*.deb $(pwd)/docker/runtime

    - name: Build the runtime docker image
      run: docker build -t $ImageName:runtime $(pwd)/docker/runtime

    - name: Run the project
      run: docker run --rm $ImageName:runtime
